---

- name: Create oc Temp Dir
  file:
    path: /tmp/oc
    state: directory

- name: Create oc Extract Temp Dir
  file:
    path: /tmp/oc/extract
    state: directory

- name: Download / Install Latest OC binary
  get_url:
    url:  https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz
    dest: /tmp/oc/oc.tar.gz
    mode: '0555'


# Since oc archive includes other file and links 
# and there is no way of just extracting oc without knowing every file you want to exclude
# going to use a temp dir and cherry pick what I want out of it
- name: Extract OC binary to temp dir
  unarchive:
    src: /tmp/oc/oc.tar.gz
    dest: /tmp/oc/extract

- name: Ensure OC Binary is in /usr/local/bin
  copy:
    src: /tmp/oc/extract/oc
    dest: /usr/local/bin/oc
    owner: root
    group: root
    mode: '0755'

- name: Remove oc Temp Dir
  file:
    path: /tmp/oc
    state: absent

- name: 'Ensure bash-completion Package is Installed via ({{ ansible_pkg_mgr }})'
  include_tasks: 'pkg-install-{{ ansible_pkg_mgr }}.yml'
  when: ansible_pkg_mgr in ('apt', 'yum', 'dnf')

- fail:
    msg: WARNING This role is not setup to deal with package manager {{ ansible_pkg_mgr }} can not verify bash-completion Package is installed, bash completions may not work
  ignore_errors: yes
  when: ansible_pkg_mgr not in ('apt', 'yum', 'dnf')

- name: Ensure kubectl symbolic link to oc exists
  file:
    src: /usr/local/bin/oc
    dest: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: '0755'
    state: link


- name: Setup bash Completion for oc
  shell: oc completion bash > /etc/bash_completion.d/oc_completion

- name: Ensure bash Completion Script has Proper File Permissions
  file:
    path: /etc/bash_completion.d/oc_completion
    owner: root
    group: root
    mode: '0644'

- name: Setup bash Completion for kubectl
  shell: kubectl completion bash > /etc/bash_completion.d/kubectl_completion

- name: Ensure bash Completion Script has Proper File Permissions
  file:
    path: /etc/bash_completion.d/kubectl_completion
    owner: root
    group: root
    mode: '0644'

- debug:
    msg: If oc or kubectl is new/updated the bash completion may not work properly until you log into a new bash shell.



